### ISSUE TITLE
Rework toolbar dropdowns

### ISSUE THREAD

**Issue by personalizedrefrigerator** [personalizedrefrigerator/js-draw#21]
# Summary
Currently, toolbar dropdowns in `js-draw` look the same on all platforms. This is the current appearance (and can be seen [here](https://js-draw.web.app/demo/)):
![Screenshot: rectangular dropdown is positioned directly below a toolbar button](https://user-images.githubusercontent.com/46334387/249253261-8dc51e09-de5b-4261-8f84-079d761cc5b7.png)
Some users have found these dropdowns initially unintuitive (e.g. discovering that they exist) and their design differs significantly from that of other apps.

The redesign will likely have different dropdown layouts for different platforms (e.g. small screen width vs large screen width).

# To-dos
- [x] Redesign dropdowns/toolbar on small-width screens
- [x] Redesign dropdowns/toolbar on large-width screens
- [x] Implement draft versions of designs ([branch](https://github.com/personalizedrefrigerator/js-draw/tree/work/sidebar-tool-properties))
    - [ ] Refactoring to allow multiple different types of toolbar layouts (without significantly changing API).
    - [ ] Implement redesign possibilities (see below)
- [x] Receive and implement feedback on drafts

# Design drafts

Note: The below sketches don't include the exact icons/colors/theming I plan to use. 

## Redesign possibility 1: Sidebars

On large screens, one option is to display tool options in a sidebar, rather than a dropdown. For example,

![Design mockup: Text tool options shown in a sidebar, rather than a dropdown](https://user-images.githubusercontent.com/46334387/249519710-707bbc48-7cbd-4afb-bf85-8dc02b5feba1.svg)

While this is a closer experience to many other applications and may be easier to navigate to, it is unclear whether the pan tool/page dropdown should have a similar sidebar or a completely different design.

At present, the "pan" dropdown looks like this:
![screenshot: pan tool dropdown: A list of buttons with icons](https://user-images.githubusercontent.com/46334387/249520484-479bc34f-1ee9-4c85-a25f-9492c4c6f147.png)

The "page" dropdown looks like this:
![screenshot: page tool dropdown](https://user-images.githubusercontent.com/46334387/249520635-c910de13-5e9e-40d6-9351-7d404bc1959e.png)

The pan dropdown might, with a sidebar, look like this:

![Image](https://user-images.githubusercontent.com/46334387/249522800-7ca4d400-71c6-46e2-8dd3-03c98d6922a4.svg)

## Redesign possibility 2: Drawer-like menu from the bottom of the screen

On narrow-width screens, it may make sense to use a menu that comes up from the bottom of the screen:

<img src="https://user-images.githubusercontent.com/46334387/249546697-df497015-b1d2-456b-bfc4-60c175f1a7dc.svg" alt="Drawer coming up from bottom of screen" width="400"/>

Tapping on a tool twice or long-pressing could show the dropdown.

**Comment by personalizedrefrigerator** [comment]
Closing for now: Possibility 2 has been implemented for quite some time.
